# Generated by Django 3.0.4 on 2020-05-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mac', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='message',
        ),
    ]
