# Generated by Django 3.0.4 on 2020-05-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mac', '0005_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
